/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc20CopySol from "./IERC20 copy.sol";
export type { ierc20CopySol };
import type * as v1 from "./V1";
export type { v1 };
export type { IERC20 } from "./IERC20";
export type { IUniswapV2Callee } from "./IUniswapV2Callee";
export type { IUniswapV2ERC20 } from "./IUniswapV2ERC20";
export type { IUniswapV2Factory } from "./IUniswapV2Factory";
export type { IUniswapV2Migrator } from "./IUniswapV2Migrator";
export type { IUniswapV2Pair } from "./IUniswapV2Pair";
export type { IUniswapV2Router01 } from "./IUniswapV2Router01";
export type { IUniswapV2Router02 } from "./IUniswapV2Router02";
export type { IWETH } from "./IWETH";
